services:
  app:
    build: .
    container_name: myfinance_app
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: myfinance_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: usuarios
      MYSQL_USER: myfinance_user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/bd_criacao.sql:/docker-entrypoint-initdb.d/1-bd_criacao.sql
      - ./database/bd_insert.sql:/docker-entrypoint-initdb.d/2-bd_insert.sql

volumes:
  db_data:
