name: Auto Tag Version

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  autotag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pegar
        id: get_last_tag
        run: |
          last_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "last_tag=$last_tag" >> $GITHUB_OUTPUT

      - name: Incrementar
        id: bump_version
        run: |
          last_tag="${{ steps.get_last_tag.outputs.last_tag }}"
          echo "Última tag: $last_tag"

          version=${last_tag#v}
          IFS='.' read -r major minor patch <<< "$version"
          patch=$((patch + 1))
          new_version="v$major.$minor.$patch"

          echo "Nova versão: $new_version"
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Criar
        env:
          NEW_VERSION: ${{ steps.bump_version.outputs.new_version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git tag "$NEW_VERSION"

          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git push origin "$NEW_VERSION"
